### ISSUE TITLE
[REFACTOR] Replace RxSwift with Combine

### ISSUE THREAD

**Issue by cardoso** [cardoso/ReduxMovieDB#26]

**Comment by pankova** [comment]
Hi! Can I help you with it?

**Comment by cardoso** [comment]
@pankova of course! Thank you!

**Comment by pankova** [comment]
@cardoso hi! Do you know Combine need iOS 13 as deployment target? Now the project target is 11.2. Are you agree to raise version?

**Comment by cardoso** [comment]
@pankova yes! Feel free to raise the version 😃
