### ISSUE TITLE
[CHORE] Update to Xcode 12/iOS 14

### ISSUE THREAD

**Issue by cardoso** [cardoso/ReduxMovieDB#46]

**Comment by M1zz** [comment]
@cardoso Hi! I want to contribute to this issue. Can I?

**Comment by cardoso** [comment]
@M1zz of course! Thank you :)

**Comment by M1zz** [comment]
@cardoso Hi can I ask something? What is meaning update to Xcode12 .

now I'm using Xcode 12 but everything is ok. and build success.

**Comment by ashishkakkad8** [comment]
I have submitted a pull request. #Hacktoberfest
